# Generated by Django 4.2.1 on 2023-05-12 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telegrambot', '0003_alter_telegramuser_language'),
    ]

    operations = [
        migrations.RenameField(
            model_name='telegramuser',
            old_name='telegram_id',
            new_name='telegram_user_id',
        ),
    ]
