# Generated by Django 4.1.6 on 2023-02-12 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_rename_avialability_book_availability_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='photo',
            field=models.ImageField(blank=True, default='default.jpg', upload_to='books/'),
        ),
    ]
