# Generated by Django 4.1.6 on 2023-03-08 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_alter_user_first_name_alter_user_last_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='content_uz',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='name_uz',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='name_uz',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='book',
            name='content_en',
        ),
        migrations.RemoveField(
            model_name='book',
            name='content_ru',
        ),
        migrations.RemoveField(
            model_name='book',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='book',
            name='name_ru',
        ),
        migrations.RemoveField(
            model_name='category',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='category',
            name='name_ru',
        ),
    ]
