# Generated by Django 4.1.6 on 2023-04-22 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_rename_content_uz_book_content_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nashriyot nomi')),
                ('logo', models.ImageField(upload_to='publishers/')),
            ],
            options={
                'verbose_name': 'Nashriyot',
                'verbose_name_plural': 'Nashriyotlar',
            },
        ),
        migrations.AddField(
            model_name='book',
            name='show_on_ad_block',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='book',
            name='publisher',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, to='catalog.publisher'),
        ),
    ]
