# Generated by Django 4.1.6 on 2023-04-25 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_publisher_book_show_on_ad_block_book_publisher'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='path',
            field=models.CharField(db_index=True, default='-', max_length=50),
        ),
    ]
