# Generated by Django 4.2.1 on 2023-05-08 19:02

from django.db import migrations, models
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_delete_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='content',
            new_name='content_uz',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='name',
            new_name='name_uz',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='name_uz',
        ),
        migrations.AddField(
            model_name='book',
            name='content_en',
            field=django_quill.fields.QuillField(),
        ),
        migrations.AddField(
            model_name='book',
            name='content_ru',
            field=django_quill.fields.QuillField(),
        ),
        migrations.AddField(
            model_name='book',
            name='name_en',
            field=models.CharField(max_length=250),
        ),
        migrations.AddField(
            model_name='book',
            name='name_ru',
            field=models.CharField(max_length=250),
        ),
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name='Nomi en'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ru',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name='Nomi ru'),
        ),
    ]
