# Generated by Django 4.2.1 on 2023-05-08 19:18

from django.db import migrations, models
import django.db.models.expressions
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_rename_content_book_content_uz_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='content_en',
            field=django_quill.fields.QuillField(default=django.db.models.expressions.CombinedExpression(models.Value('EN'), '+', models.F(models.TextField()))),
        ),
        migrations.AlterField(
            model_name='book',
            name='content_ru',
            field=django_quill.fields.QuillField(default=django.db.models.expressions.CombinedExpression(models.Value('RU'), '+', models.F(models.TextField()))),
        ),
        migrations.AlterField(
            model_name='book',
            name='name_en',
            field=models.CharField(default=django.db.models.expressions.CombinedExpression(models.Value('EN'), '+', models.F('name_uz')), max_length=250),
        ),
        migrations.AlterField(
            model_name='book',
            name='name_ru',
            field=models.CharField(default=django.db.models.expressions.CombinedExpression(models.Value('RU'), '+', models.F('name_uz')), max_length=250),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_en',
            field=models.CharField(blank=True, default=django.db.models.expressions.CombinedExpression(models.Value('EN'), '+', models.F('name_uz')), max_length=45, null=True, verbose_name='Nomi en'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_ru',
            field=models.CharField(blank=True, default=django.db.models.expressions.CombinedExpression(models.Value('RU'), '+', models.F('name_uz')), max_length=45, null=True, verbose_name='Nomi ru'),
        ),
    ]
