# Generated by Django 4.2.1 on 2023-05-08 20:03

from django.db import migrations, models
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_alter_book_content_en_alter_book_content_ru_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='content_en',
            field=django_quill.fields.QuillField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='content_ru',
            field=django_quill.fields.QuillField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='content_uz',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='name_en',
            field=models.CharField(default=None, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='name_ru',
            field=models.CharField(default=None, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='name_uz',
            field=models.CharField(default=None, max_length=250, null=True),
        ),
    ]
