# Generated by Django 4.2.1 on 2023-05-08 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0018_alter_book_content_en_alter_book_content_ru_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name_en',
            field=models.CharField(default=None, max_length=45, null=True, verbose_name='Nomi en'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_ru',
            field=models.CharField(default=None, max_length=45, null=True, verbose_name='Nomi ru'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_uz',
            field=models.CharField(default=None, max_length=45, null=True, verbose_name='Nomi uz'),
        ),
    ]
