# Generated by Django 4.2.1 on 2023-05-16 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0021_alter_book_content_en_alter_book_content_ru_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='photo',
            field=models.ImageField(upload_to='blocks/'),
        ),
    ]
