# Generated by Django 4.1.6 on 2023-05-01 21:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0012_category_path'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('zip', models.CharField(max_length=10)),
                ('total_price', models.IntegerField()),
                ('status', models.SmallIntegerField(choices=[(0, 'Yangi'), (1, 'Qabul qilingan'), (2, 'Inkor qilingan')])),
                ('payment_status', models.SmallIntegerField(choices=[(0, 'Noaniq'), (1, 'Jarayonda'), (2, "To'langan"), (3, 'Bekor qilingan')])),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='catalog.book')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='order.order')),
            ],
        ),
    ]
